plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.hfpdetector'
    // 升级编译版本，确保不触发高版本编译器的降级警告
    compileSdk 34

    defaultConfig {
        applicationId "com.example.hfpdetector"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
